-- PostgreSQL Schema for Supabase (TraceRoo)

-- 1. Master Definitions
CREATE TABLE IF NOT EXISTS master_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    def_type TEXT NOT NULL,
    def_value TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE(def_type, def_value)
);

-- 2. Locations
CREATE TABLE IF NOT EXISTS locations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    type TEXT,
    category TEXT,
    parent_id UUID REFERENCES locations(id),
    status TEXT DEFAULT 'ACTIVE',
    
    address_line1 TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    zip_code TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    
    capacity_volume DOUBLE PRECISION,
    capacity_weight DOUBLE PRECISION,
    current_utilization DOUBLE PRECISION,
    
    gln TEXT,
    rfid_reader_id TEXT,
    is_quarantine BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Materials
CREATE TABLE IF NOT EXISTS materials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    
    type TEXT,
    category TEXT,
    class TEXT,
    
    base_uom TEXT,
    procurement_type TEXT,
    
    is_batch_managed BOOLEAN DEFAULT FALSE,
    is_serial_managed BOOLEAN DEFAULT FALSE,
    shelf_life_days INTEGER,
    min_rem_shelf_life INTEGER,
    serial_format TEXT,
    
    min_stock DOUBLE PRECISION,
    max_stock DOUBLE PRECISION,
    reorder_point DOUBLE PRECISION,
    safety_stock DOUBLE PRECISION,
    
    gross_weight DOUBLE PRECISION,
    net_weight DOUBLE PRECISION,
    weight_uom TEXT,
    length DOUBLE PRECISION,
    width DOUBLE PRECISION,
    height DOUBLE PRECISION,
    dimension_uom TEXT,
    
    hazmat_code TEXT,
    storage_condition TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_locations_parent ON locations(parent_id);
CREATE INDEX IF NOT EXISTS idx_materials_type ON materials(type);
