-- =====================================================
-- TraceRoo Phase 1: Core Inventory & Scanning
-- Supabase Migration Script
-- Run this in Supabase SQL Editor
-- =====================================================

-- =====================================================
-- 1. SERIAL NUMBER POOL TABLE
-- Manages pre-generated serial numbers for items
-- =====================================================
CREATE TABLE IF NOT EXISTS serial_number_pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id UUID NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
    batch_number TEXT,
    serial_number TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'RESERVED' CHECK (status IN ('RESERVED', 'ASSIGNED', 'CONSUMED', 'VOIDED')),
    inventory_id BIGINT,
    reserved_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    assigned_at TIMESTAMP WITH TIME ZONE,
    created_by TEXT
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_serial_pool_material ON serial_number_pool(material_id);
CREATE INDEX IF NOT EXISTS idx_serial_pool_status ON serial_number_pool(status);
CREATE INDEX IF NOT EXISTS idx_serial_pool_batch ON serial_number_pool(batch_number);
CREATE INDEX IF NOT EXISTS idx_serial_pool_serial ON serial_number_pool(serial_number);

-- =====================================================
-- 2. ENHANCE INVENTORY TABLE
-- Add columns for quality, dates, and parent tracking
-- =====================================================
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS quality_status TEXT DEFAULT 'PENDING' 
    CHECK (quality_status IN ('PENDING', 'PASS', 'FAIL', 'HOLD'));
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS manufactured_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS current_owner TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS parent_container_type TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS parent_container_id BIGINT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS confirmed_by TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS scan_location_id UUID REFERENCES locations(id);

-- Update status check constraint to include PRE_INVENTORY
-- First drop the existing constraint if it exists
DO $$ 
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'inventory_status_check'
    ) THEN
        ALTER TABLE inventory DROP CONSTRAINT inventory_status_check;
    END IF;
END $$;

-- Add new constraint with PRE_INVENTORY status
ALTER TABLE inventory ADD CONSTRAINT inventory_status_check 
    CHECK (status IN ('PRE_INVENTORY', 'REGISTERED', 'ACTIVE', 'PACKED', 'SHIPPED', 'DELIVERED', 'CONSUMED', 'RETURNED', 'SCRAPPED'));

-- =====================================================
-- 3. ENHANCE MATERIALS TABLE
-- Add missing attributes from TNT requirements
-- =====================================================
ALTER TABLE materials ADD COLUMN IF NOT EXISTS ean TEXT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS upc TEXT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS country_of_origin TEXT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS state TEXT; -- Solid, Liquid, Dust, Gas
ALTER TABLE materials ADD COLUMN IF NOT EXISTS class TEXT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS material_group TEXT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS storage_type TEXT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS trade_uom TEXT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS trade_weight DOUBLE PRECISION;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS trade_length DOUBLE PRECISION;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS trade_width DOUBLE PRECISION;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS trade_height DOUBLE PRECISION;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS is_packaged BOOLEAN DEFAULT FALSE;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS is_fragile BOOLEAN DEFAULT FALSE;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS is_military BOOLEAN DEFAULT FALSE;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS is_high_value BOOLEAN DEFAULT FALSE;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS is_env_sensitive BOOLEAN DEFAULT FALSE;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS packaging_hierarchy_id BIGINT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS serial_format TEXT DEFAULT 'SN-{DDMMYYYY}-{XXXXX}';

-- =====================================================
-- 4. ENHANCE PACKAGING_LEVEL TABLE
-- Add serial format and label dimensions
-- =====================================================
ALTER TABLE packaging_level ADD COLUMN IF NOT EXISTS serial_format TEXT;
ALTER TABLE packaging_level ADD COLUMN IF NOT EXISTS label_width_mm DOUBLE PRECISION;
ALTER TABLE packaging_level ADD COLUMN IF NOT EXISTS label_height_mm DOUBLE PRECISION;
ALTER TABLE packaging_level ADD COLUMN IF NOT EXISTS is_fragile BOOLEAN DEFAULT FALSE;
ALTER TABLE packaging_level ADD COLUMN IF NOT EXISTS is_hazardous BOOLEAN DEFAULT FALSE;

-- =====================================================
-- 5. ENHANCE LABEL_TEMPLATES TABLE
-- Add versioning and barcode symbology
-- =====================================================
ALTER TABLE label_templates ADD COLUMN IF NOT EXISTS version TEXT DEFAULT '1.0';
ALTER TABLE label_templates ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ACTIVE' 
    CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED'));
ALTER TABLE label_templates ADD COLUMN IF NOT EXISTS label_width_mm DOUBLE PRECISION;
ALTER TABLE label_templates ADD COLUMN IF NOT EXISTS label_height_mm DOUBLE PRECISION;
ALTER TABLE label_templates ADD COLUMN IF NOT EXISTS barcode_symbology TEXT DEFAULT 'QR' 
    CHECK (barcode_symbology IN ('QR', 'CODE128', 'EAN13', 'DATAMATRIX', 'GS1_128'));

-- =====================================================
-- 6. ROW LEVEL SECURITY (RLS) FOR SERIAL_NUMBER_POOL
-- Enable RLS and create policies
-- =====================================================
ALTER TABLE serial_number_pool ENABLE ROW LEVEL SECURITY;

-- Allow all operations for authenticated users (adjust as needed)
CREATE POLICY "Enable all access for authenticated users" ON serial_number_pool
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Allow anonymous read access (for public queries)
CREATE POLICY "Enable read access for anon" ON serial_number_pool
    FOR SELECT
    TO anon
    USING (true);

-- =====================================================
-- 7. HELPER FUNCTION: Generate Serial Number
-- Generates serial in format SN-DDMMYYYY-00001
-- =====================================================
CREATE OR REPLACE FUNCTION generate_serial_number(
    p_material_id UUID,
    p_batch_number TEXT DEFAULT NULL
)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    v_date_part TEXT;
    v_sequence INT;
    v_serial TEXT;
BEGIN
    -- Get current date in DDMMYYYY format
    v_date_part := TO_CHAR(CURRENT_DATE, 'DDMMYYYY');
    
    -- Get the next sequence number for this material and date
    SELECT COALESCE(MAX(
        CAST(SUBSTRING(serial_number FROM '[0-9]+$') AS INTEGER)
    ), 0) + 1
    INTO v_sequence
    FROM serial_number_pool
    WHERE material_id = p_material_id
    AND serial_number LIKE 'SN-' || v_date_part || '-%';
    
    -- Format serial number with 5-digit sequence
    v_serial := 'SN-' || v_date_part || '-' || LPAD(v_sequence::TEXT, 5, '0');
    
    RETURN v_serial;
END;
$$;

-- =====================================================
-- 8. HELPER FUNCTION: Reserve Serial Numbers
-- Reserves a range of serial numbers for a batch
-- =====================================================
CREATE OR REPLACE FUNCTION reserve_serial_numbers(
    p_material_id UUID,
    p_batch_number TEXT,
    p_quantity INT,
    p_created_by TEXT DEFAULT NULL
)
RETURNS TABLE(serial_number TEXT, id BIGINT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_date_part TEXT;
    v_start_sequence INT;
    v_i INT;
    v_serial TEXT;
BEGIN
    -- Get current date in DDMMYYYY format
    v_date_part := TO_CHAR(CURRENT_DATE, 'DDMMYYYY');
    
    -- Get the next starting sequence number
    SELECT COALESCE(MAX(
        CAST(SUBSTRING(snp.serial_number FROM '[0-9]+$') AS INTEGER)
    ), 0) + 1
    INTO v_start_sequence
    FROM serial_number_pool snp
    WHERE snp.material_id = p_material_id
    AND snp.serial_number LIKE 'SN-' || v_date_part || '-%';
    
    -- Insert each serial number
    FOR v_i IN 0..(p_quantity - 1) LOOP
        v_serial := 'SN-' || v_date_part || '-' || LPAD((v_start_sequence + v_i)::TEXT, 5, '0');
        
        INSERT INTO serial_number_pool (material_id, batch_number, serial_number, status, created_by)
        VALUES (p_material_id, p_batch_number, v_serial, 'RESERVED', p_created_by)
        RETURNING serial_number_pool.serial_number, serial_number_pool.id
        INTO serial_number, id;
        
        RETURN NEXT;
    END LOOP;
    
    RETURN;
END;
$$;

-- =====================================================
-- 9. HELPER FUNCTION: Assign Serial to Inventory
-- Links a serial number to an inventory record
-- =====================================================
CREATE OR REPLACE FUNCTION assign_serial_to_inventory(
    p_serial_number TEXT,
    p_inventory_id BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE serial_number_pool
    SET 
        status = 'ASSIGNED',
        inventory_id = p_inventory_id,
        assigned_at = NOW()
    WHERE serial_number = p_serial_number
    AND status = 'RESERVED';
    
    RETURN FOUND;
END;
$$;

-- =====================================================
-- 10. VIEW: Available Serials by Material
-- =====================================================
CREATE OR REPLACE VIEW available_serials AS
SELECT 
    snp.id,
    snp.serial_number,
    snp.material_id,
    m.code AS material_code,
    m.name AS material_name,
    snp.batch_number,
    snp.status,
    snp.reserved_at
FROM serial_number_pool snp
JOIN materials m ON m.id = snp.material_id
WHERE snp.status = 'RESERVED';

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================
