-- =====================================================
-- TraceRoo Phase 4: Shipping & Events
-- Supabase Migration Script
-- Run this in Supabase SQL Editor AFTER Phase 3
-- =====================================================

-- =====================================================
-- 1. SHIPMENT TABLE
-- Tracks shipments from origin to destination
-- =====================================================
CREATE TABLE IF NOT EXISTS shipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_number TEXT UNIQUE NOT NULL,
    origin_location_id UUID REFERENCES locations(id),
    destination_location_id UUID REFERENCES locations(id),
    status TEXT DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'LOADING', 'DISPATCHED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED')),
    carrier TEXT,
    tracking_number TEXT,
    vehicle_number TEXT,
    driver_name TEXT,
    driver_contact TEXT,
    expected_delivery_date TIMESTAMP WITH TIME ZONE,
    dispatched_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by TEXT
);

CREATE INDEX IF NOT EXISTS idx_shipment_status ON shipment(status);
CREATE INDEX IF NOT EXISTS idx_shipment_number ON shipment(shipment_number);
CREATE INDEX IF NOT EXISTS idx_shipment_origin ON shipment(origin_location_id);
CREATE INDEX IF NOT EXISTS idx_shipment_destination ON shipment(destination_location_id);

-- =====================================================
-- 2. SHIPMENT ITEMS TABLE
-- Links containers/inventory to shipments
-- =====================================================
CREATE TABLE IF NOT EXISTS shipment_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES shipment(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL CHECK (item_type IN ('INVENTORY', 'BOX', 'PALLET', 'SHIPPING_CONTAINER')),
    item_id BIGINT NOT NULL,
    quantity INTEGER DEFAULT 1,
    added_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(shipment_id, item_type, item_id)
);

CREATE INDEX IF NOT EXISTS idx_shipment_item_shipment ON shipment_item(shipment_id);
CREATE INDEX IF NOT EXISTS idx_shipment_item_type ON shipment_item(item_type, item_id);

-- =====================================================
-- 3. OWNERSHIP TRANSFER TABLE
-- Tracks custody chain
-- =====================================================
CREATE TABLE IF NOT EXISTS ownership_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('INVENTORY', 'BOX', 'PALLET', 'SHIPMENT')),
    entity_id BIGINT NOT NULL,
    from_owner TEXT,
    to_owner TEXT NOT NULL,
    from_location_id UUID REFERENCES locations(id),
    to_location_id UUID REFERENCES locations(id),
    transfer_type TEXT DEFAULT 'HANDOVER' CHECK (transfer_type IN ('HANDOVER', 'SHIPMENT', 'RETURN', 'INTERNAL')),
    transferred_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    transfer_event_id BIGINT REFERENCES trace_event(id),
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_ownership_entity ON ownership_transfer(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_ownership_to ON ownership_transfer(to_owner);

-- =====================================================
-- 4. ROW LEVEL SECURITY
-- =====================================================
ALTER TABLE shipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipment_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE ownership_transfer ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for authenticated users" ON shipment
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable read access for anon" ON shipment
    FOR SELECT TO anon USING (true);

CREATE POLICY "Enable all access for authenticated users" ON shipment_item
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable read access for anon" ON shipment_item
    FOR SELECT TO anon USING (true);

CREATE POLICY "Enable all access for authenticated users" ON ownership_transfer
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable read access for anon" ON ownership_transfer
    FOR SELECT TO anon USING (true);

-- =====================================================
-- 5. FUNCTION: Generate Shipment Number
-- Format: SHP-DDMMYYYY-XXXXX
-- =====================================================
CREATE OR REPLACE FUNCTION generate_shipment_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    v_date_part TEXT;
    v_sequence INT;
    v_number TEXT;
BEGIN
    v_date_part := TO_CHAR(CURRENT_DATE, 'DDMMYYYY');
    
    SELECT COALESCE(MAX(
        CAST(SUBSTRING(shipment_number FROM '[0-9]+$') AS INTEGER)
    ), 0) + 1
    INTO v_sequence
    FROM shipment
    WHERE shipment_number LIKE 'SHP-' || v_date_part || '-%';
    
    v_number := 'SHP-' || v_date_part || '-' || LPAD(v_sequence::TEXT, 5, '0');
    
    RETURN v_number;
END;
$$;

-- =====================================================
-- 6. FUNCTION: Create Shipment
-- Creates a new shipment with auto-generated number
-- =====================================================
CREATE OR REPLACE FUNCTION create_shipment(
    p_origin_location_id UUID,
    p_destination_location_id UUID,
    p_carrier TEXT DEFAULT NULL,
    p_expected_delivery_date TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    p_notes TEXT DEFAULT NULL,
    p_created_by TEXT DEFAULT NULL
)
RETURNS shipment
LANGUAGE plpgsql
AS $$
DECLARE
    v_number TEXT;
    v_shipment shipment;
BEGIN
    v_number := generate_shipment_number();
    
    INSERT INTO shipment (
        shipment_number, origin_location_id, destination_location_id,
        carrier, expected_delivery_date, notes, created_by
    )
    VALUES (
        v_number, p_origin_location_id, p_destination_location_id,
        p_carrier, p_expected_delivery_date, p_notes, p_created_by
    )
    RETURNING * INTO v_shipment;
    
    RETURN v_shipment;
END;
$$;

-- =====================================================
-- 7. FUNCTION: Add Items to Shipment
-- =====================================================
CREATE OR REPLACE FUNCTION add_items_to_shipment(
    p_shipment_id BIGINT,
    p_item_type TEXT,
    p_item_ids BIGINT[]
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_item_id BIGINT;
    v_added_count INT := 0;
    v_errors JSONB := '[]'::JSONB;
BEGIN
    FOREACH v_item_id IN ARRAY p_item_ids LOOP
        BEGIN
            INSERT INTO shipment_item (shipment_id, item_type, item_id)
            VALUES (p_shipment_id, p_item_type, v_item_id);
            v_added_count := v_added_count + 1;
        EXCEPTION WHEN unique_violation THEN
            v_errors := v_errors || jsonb_build_object('item_id', v_item_id, 'error', 'Already in shipment');
        END;
    END LOOP;
    
    RETURN jsonb_build_object('success', true, 'added_count', v_added_count, 'errors', v_errors);
END;
$$;

-- =====================================================
-- 8. FUNCTION: Dispatch Shipment
-- =====================================================
CREATE OR REPLACE FUNCTION dispatch_shipment(
    p_shipment_id BIGINT,
    p_vehicle_number TEXT DEFAULT NULL,
    p_driver_name TEXT DEFAULT NULL,
    p_driver_contact TEXT DEFAULT NULL
)
RETURNS shipment
LANGUAGE plpgsql
AS $$
DECLARE
    v_shipment shipment;
    v_event_id BIGINT;
BEGIN
    -- Update shipment status
    UPDATE shipment
    SET status = 'DISPATCHED',
        dispatched_at = NOW(),
        vehicle_number = COALESCE(p_vehicle_number, vehicle_number),
        driver_name = COALESCE(p_driver_name, driver_name),
        driver_contact = COALESCE(p_driver_contact, driver_contact)
    WHERE id = p_shipment_id
    RETURNING * INTO v_shipment;
    
    -- Create trace event
    INSERT INTO trace_event (
        event_type, event_category, event_timestamp, location,
        notes, status, shipment_id
    )
    VALUES (
        'DISPATCH', 'SHIPMENT', NOW(),
        (SELECT name FROM locations WHERE id = v_shipment.origin_location_id),
        'Shipment ' || v_shipment.shipment_number || ' dispatched',
        'SUCCESS', p_shipment_id
    )
    RETURNING id INTO v_event_id;
    
    -- Update all items in shipment to SHIPPED status
    UPDATE inventory
    SET status = 'SHIPPED'
    WHERE id IN (
        SELECT item_id FROM shipment_item 
        WHERE shipment_id = p_shipment_id AND item_type = 'INVENTORY'
    );
    
    UPDATE container_unit
    SET status = 'SHIPPED'
    WHERE id IN (
        SELECT item_id FROM shipment_item 
        WHERE shipment_id = p_shipment_id AND item_type IN ('BOX', 'PALLET', 'SHIPPING_CONTAINER')
    );
    
    RETURN v_shipment;
END;
$$;

-- =====================================================
-- 9. FUNCTION: Receive Shipment / Mark Delivered
-- =====================================================
CREATE OR REPLACE FUNCTION receive_shipment(
    p_shipment_id BIGINT,
    p_received_by TEXT DEFAULT NULL
)
RETURNS shipment
LANGUAGE plpgsql
AS $$
DECLARE
    v_shipment shipment;
    v_event_id BIGINT;
BEGIN
    -- Update shipment status
    UPDATE shipment
    SET status = 'DELIVERED',
        delivered_at = NOW()
    WHERE id = p_shipment_id
    RETURNING * INTO v_shipment;
    
    -- Create trace event
    INSERT INTO trace_event (
        event_type, event_category, event_timestamp, location,
        notes, status, shipment_id, "user"
    )
    VALUES (
        'RECEIVE', 'SHIPMENT', NOW(),
        (SELECT name FROM locations WHERE id = v_shipment.destination_location_id),
        'Shipment ' || v_shipment.shipment_number || ' delivered',
        'SUCCESS', p_shipment_id, p_received_by
    )
    RETURNING id INTO v_event_id;
    
    -- Update all items in shipment to DELIVERED status
    UPDATE inventory
    SET status = 'DELIVERED',
        location_id = v_shipment.destination_location_id
    WHERE id IN (
        SELECT item_id FROM shipment_item 
        WHERE shipment_id = p_shipment_id AND item_type = 'INVENTORY'
    );
    
    UPDATE container_unit
    SET status = 'DELIVERED',
        location_id = v_shipment.destination_location_id
    WHERE id IN (
        SELECT item_id FROM shipment_item 
        WHERE shipment_id = p_shipment_id AND item_type IN ('BOX', 'PALLET', 'SHIPPING_CONTAINER')
    );
    
    -- Create ownership transfer record
    INSERT INTO ownership_transfer (
        entity_type, entity_id, from_owner, to_owner,
        from_location_id, to_location_id, transfer_type, transfer_event_id
    )
    VALUES (
        'SHIPMENT', p_shipment_id,
        (SELECT name FROM locations WHERE id = v_shipment.origin_location_id),
        (SELECT name FROM locations WHERE id = v_shipment.destination_location_id),
        v_shipment.origin_location_id, v_shipment.destination_location_id,
        'SHIPMENT', v_event_id
    );
    
    RETURN v_shipment;
END;
$$;

-- =====================================================
-- 10. VIEW: Shipment Summary
-- =====================================================
CREATE OR REPLACE VIEW shipment_summary AS
SELECT 
    s.id,
    s.shipment_number,
    s.status,
    s.carrier,
    s.tracking_number,
    ol.name as origin_name,
    ol.code as origin_code,
    dl.name as destination_name,
    dl.code as destination_code,
    s.expected_delivery_date,
    s.dispatched_at,
    s.delivered_at,
    s.created_at,
    (SELECT COUNT(*) FROM shipment_item WHERE shipment_id = s.id) as item_count
FROM shipment s
LEFT JOIN locations ol ON s.origin_location_id = ol.id
LEFT JOIN locations dl ON s.destination_location_id = dl.id
ORDER BY s.created_at DESC;

-- =====================================================
-- 11. FUNCTION: Get Shipment Items with Details
-- =====================================================
CREATE OR REPLACE FUNCTION get_shipment_items(p_shipment_id BIGINT)
RETURNS TABLE (
    item_type TEXT,
    item_id BIGINT,
    serial_number TEXT,
    item_name TEXT,
    status TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        si.item_type,
        si.item_id,
        CASE 
            WHEN si.item_type = 'INVENTORY' THEN i.serial_number
            ELSE cu.serial_number
        END,
        CASE 
            WHEN si.item_type = 'INVENTORY' THEN m.name
            ELSE cu.container_type
        END,
        CASE 
            WHEN si.item_type = 'INVENTORY' THEN i.status
            ELSE cu.status
        END
    FROM shipment_item si
    LEFT JOIN inventory i ON si.item_type = 'INVENTORY' AND si.item_id = i.id
    LEFT JOIN materials m ON i.material_id = m.id
    LEFT JOIN container_unit cu ON si.item_type IN ('BOX', 'PALLET', 'SHIPPING_CONTAINER') AND si.item_id = cu.id
    WHERE si.shipment_id = p_shipment_id;
END;
$$;

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================
